version: '3.7'

services:
  
  authapi-postgres:
    image: postgres
    container_name: authapi-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "abcd1234"
    ports:
      - "15432:5432"
    networks:
      - authapi-net
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    restart: always
    privileged: true
    tty: true

  authapi-pgadmin4:
    image: dpage/pgadmin4
    container_name: authapi-pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@test.com"
      PGADMIN_DEFAULT_PASSWORD: "123"
    ports:
      - "16543:80"
    depends_on:
      - authapi-postgres
    networks:
      - authapi-net    
    links:
      - authapi-postgres:db      
    restart: always
    privileged: true
    tty: true

  authapi-migrations:
    image: authapi-migrations
    container_name: authapi-migrations
    build:
      context: .
      dockerfile: Dockerfile.migrations
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DATABASE_CONNECTION_STRING: "Host=db;Port=5432;Pooling=true;Database=AuthDb;User Id=postgres;Password=abcd1234;"
    depends_on:
      - authapi-postgres      
    networks:
      - authapi-net     
    links:
      - authapi-postgres:db
    privileged: true
    tty: true

  authapi-api:
    image: authapi-api
    container_name: authapi-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DATABASE_CONNECTION_STRING: "Host=db;Port=5432;Pooling=true;Database=AuthDb;User Id=postgres;Password=abcd1234;"
    ports:
      - "5000:80"
    depends_on:
      - authapi-postgres      
    networks:
      - authapi-net     
    links:
      - authapi-postgres:db         
    restart: always
    privileged: true
    tty: true

networks:
  authapi-net:
    external: true