# ---- Run Build ----
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
ENV PATH="${PATH}:/root/.dotnet/tools"
RUN dotnet tool install --global dotnet-ef --version 3.1.3
COPY ./src /app/
WORKDIR /app/Auth.Api
RUN dotnet restore
RUN dotnet publish -c Release -o out
CMD dotnet ef database update --project ../Auth.Api